apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-processing-service
  namespace: erp-dev
  labels:
    app: approval-processing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: approval-processing-service
  template:
    metadata:
      labels:
        app: approval-processing-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - approval-processing-service
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: approval-processing-service
        image: 806332783810.dkr.ecr.ap-northeast-2.amazonaws.com/erp/approval-processing-service:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
        ports:
        - containerPort: 8083
          name: http
        - containerPort: 9090
          name: grpc
        env:
        - name: GRPC_CLIENT_APPROVALREQUESTSERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: GRPC_APPROVAL_REQUEST_ADDRESS
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: /process/1
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /process/1
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
