server:
  port: 8082

spring:
  application:
    name: approval-request-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/erp}

employee:
  service:
    url: ${EMPLOYEE_SERVICE_URL:http://employee-service:8081}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

grpc:
  server:
    port: 9091
  client:
    approvalprocessingservice:
      address: ${APPROVAL_PROCESSING_GRPC_ADDRESS:static://approval-processing-service:9090}
      negotiationType: plaintext
