apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-config
  namespace: erp-dev
data:
  # MySQL (Employee Service)
  MYSQL_HOST: "erp-dev-mysql.cniqqqqiyu1n.ap-northeast-2.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "erp"
  
  # MongoDB (Approval Request Service)
  MONGODB_URI: "mongodb+srv://erp_user:2dvZYzleqGYdyANc@erp-dev-cluster.4fboxqw.mongodb.net/erp"
  
  # Redis (Notification Service)
  REDIS_HOST: "erp-dev-redis.jmz0hq.0001.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  
  # Service URLs
  EMPLOYEE_SERVICE_URL: "http://employee-service:8081"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  
  # gRPC Addresses
  GRPC_APPROVAL_PROCESSING_ADDRESS: "static://approval-processing-service:9090"
  GRPC_APPROVAL_REQUEST_ADDRESS: "static://approval-request-service:9091"
