apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: erp-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: erp-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USERNAME
    remoteRef:
      key: erp/dev/mysql
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: erp/dev/mysql
      property: password
  - secretKey: MYSQL_HOST
    remoteRef:
      key: erp/dev/mysql
      property: host
  - secretKey: MYSQL_PORT
    remoteRef:
      key: erp/dev/mysql
      property: port
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: erp/dev/mysql
      property: database
