server:
  port: 8083

spring:
  application:
    name: approval-processing-service

grpc:
  server:
    port: 9090
  client:
    approvalrequestservice:
      address: ${APPROVAL_REQUEST_GRPC_ADDRESS:static://approval-request-service:9091}
      negotiationType: plaintext
